### ISSUE TITLE
export results to CSV

### ISSUE THREAD

**Issue by mksndz** [GIL-GALILEO/new-titles-api#19]

**Comment by seanpurcell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Titles 8/2](https://trello.com/c/uIIeR7yy/1-new-titles-8-2)

**Comment by seanpurcell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate exporting the results to csv using datatables](https://trello.com/c/PENz58Ru/8-investigate-exporting-the-results-to-csv-using-datatables)
